name: Build and run all tests
on:
    push:
        branches:
            - main
    pull_request:

jobs:
    test:
        if: ${{ !(contains(github.head_ref, 'ui/')) || !(contains(github.head_ref, 'cms/')) }}
        strategy:
            matrix:
                go-version: [1.16.x, 1.17.x]
                os: [ubuntu-latest, macos-latest]
                mongodb-version: ["5.0"]
                redis-version: ["6.2.6"]

        runs-on: ubuntu-latest
        steps:
            - name: Get the version
              id: get_version
              run: echo ::set-output name=tag::$(echo ${GITHUB_SHA:8})

            - name: Set up Go
              uses: actions/setup-go@v2
              with:
                  go-version: ${{ matrix.go-version }}

            - name: Cache go modules
              uses: actions/cache@v1
              with:
                  path: ~/go/pkg/mod
                  key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
                  restore-keys: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}

            - name: Check out code
              uses: actions/checkout@v2

            - name: Get and verify dependencies
              run: go mod download && go mod verify

            - name: Build app to make sure there are zero issues
              run: go build -o convoy-cli ./cmd

            - name: Go vet
              run: go vet ./...

            - name: Run integration tests
              run: make integration_tests
